/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Class.DoanhThuThang;
import Class.SoLuongThang;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author trisu
 */
public class QuanLy extends javax.swing.JFrame {

    /**
     * Creates new form testFrame
     */
    public QuanLy() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Quanly = new javax.swing.JTabbedPane();
        DoanhThuThang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doanhThuThangTable = new javax.swing.JTable();
        reportPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ThongKeBtn = new javax.swing.JButton();
        yearLabelDoanhThu = new javax.swing.JLabel();
        namDropList = new javax.swing.JComboBox<>();
        SoLuongThang = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        doanhThuThangTable1 = new javax.swing.JTable();
        reportPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        yearLabelDoanhThu1 = new javax.swing.JLabel();
        namDropList1 = new javax.swing.JComboBox<>();
        ThongKeBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(861, 653));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        DoanhThuThang.setBackground(new java.awt.Color(255, 255, 255));

        doanhThuThangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tháng", "Tổng doanh thu"
            }
        ));
        doanhThuThangTable.setFocusable(false);
        doanhThuThangTable.setGridColor(new java.awt.Color(255, 255, 255));
        doanhThuThangTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        doanhThuThangTable.setRowHeight(25);
        doanhThuThangTable.setSelectionBackground(new java.awt.Color(232, 57, 95));
        doanhThuThangTable.setShowVerticalLines(false);
        doanhThuThangTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(doanhThuThangTable);
        if (doanhThuThangTable.getColumnModel().getColumnCount() > 0) {
            doanhThuThangTable.getColumnModel().getColumn(0).setResizable(false);
        }

        reportPanel.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));

        ThongKeBtn.setBackground(new java.awt.Color(255, 153, 153));
        ThongKeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ThongKeBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThongKeBtn.setText("Thống kê");
        ThongKeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeBtnActionPerformed(evt);
            }
        });

        yearLabelDoanhThu.setText("Năm");

        namDropList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021" }));
        namDropList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namDropListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yearLabelDoanhThu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namDropList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ThongKeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThongKeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearLabelDoanhThu)
                    .addComponent(namDropList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DoanhThuThangLayout = new javax.swing.GroupLayout(DoanhThuThang);
        DoanhThuThang.setLayout(DoanhThuThangLayout);
        DoanhThuThangLayout.setHorizontalGroup(
            DoanhThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoanhThuThangLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(DoanhThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        DoanhThuThangLayout.setVerticalGroup(
            DoanhThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoanhThuThangLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(DoanhThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DoanhThuThangLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        Quanly.addTab("Thống kê doanh thu", DoanhThuThang);

        SoLuongThang.setBackground(new java.awt.Color(255, 255, 255));

        doanhThuThangTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tháng", "Tổng số lượng"
            }
        ));
        doanhThuThangTable1.setFocusable(false);
        doanhThuThangTable1.setOpaque(false);
        doanhThuThangTable1.setRowHeight(25);
        doanhThuThangTable1.setRowMargin(0);
        doanhThuThangTable1.setSelectionBackground(new java.awt.Color(232, 57, 95));
        doanhThuThangTable1.setShowVerticalLines(false);
        doanhThuThangTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(doanhThuThangTable1);
        if (doanhThuThangTable1.getColumnModel().getColumnCount() > 0) {
            doanhThuThangTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        reportPanel1.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout reportPanel1Layout = new javax.swing.GroupLayout(reportPanel1);
        reportPanel1.setLayout(reportPanel1Layout);
        reportPanel1Layout.setHorizontalGroup(
            reportPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        reportPanel1Layout.setVerticalGroup(
            reportPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));

        yearLabelDoanhThu1.setText("Năm");

        namDropList1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021" }));
        namDropList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namDropList1ActionPerformed(evt);
            }
        });

        ThongKeBtn1.setBackground(new java.awt.Color(255, 153, 153));
        ThongKeBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ThongKeBtn1.setForeground(new java.awt.Color(255, 255, 255));
        ThongKeBtn1.setText("Thống kê");
        ThongKeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yearLabelDoanhThu1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namDropList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(ThongKeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabelDoanhThu1)
                    .addComponent(namDropList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThongKeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SoLuongThangLayout = new javax.swing.GroupLayout(SoLuongThang);
        SoLuongThang.setLayout(SoLuongThangLayout);
        SoLuongThangLayout.setHorizontalGroup(
            SoLuongThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SoLuongThangLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(SoLuongThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(reportPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        SoLuongThangLayout.setVerticalGroup(
            SoLuongThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SoLuongThangLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(SoLuongThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SoLuongThangLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        Quanly.addTab("Thống kê số lượng bán hàng", SoLuongThang);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Quanly, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Quanly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namDropListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namDropListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namDropListActionPerformed

    private void ThongKeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeBtnActionPerformed
        
        String year = namDropList.getSelectedItem().toString();
        ArrayList<DoanhThuThang> list = null;
        list = DBController.DBController.getDoanhThuThang(year);
        //Bảng table
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tháng");
        model.addColumn("Tổng doanh thu");
        
        //Biểu đồ
        DefaultCategoryDataset  dcd = new DefaultCategoryDataset();
        
        for(DoanhThuThang dt: list){
            model.addRow(dt.toArray());
            dcd.setValue(dt.getTongTien(), "Số tiền", dt.getThang());
        }
        doanhThuThangTable.setModel(model);
        
        JFreeChart jchart = ChartFactory.createBarChart3D("Doanh thu trong năm "+year, "Tháng", "Doanh thu (VNĐ)", dcd, PlotOrientation.VERTICAL, true, true, false);
        
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.BLUE);
        
        ChartPanel chartPanel = new ChartPanel(jchart);
        
        reportPanel.removeAll();
        reportPanel.setLayout(new BorderLayout());
        reportPanel.add(chartPanel, BorderLayout.NORTH);
        reportPanel.updateUI();
        
    }//GEN-LAST:event_ThongKeBtnActionPerformed

    private void namDropList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namDropList1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namDropList1ActionPerformed

    private void ThongKeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeBtn1ActionPerformed
        String year = namDropList1.getSelectedItem().toString();
        ArrayList<SoLuongThang> list = DBController.DBController.getSoLuongThang(year);

        //Bảng table
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tháng");
        model.addColumn("Tổng số lượng");

        //Biểu đồ
        DefaultCategoryDataset  dcd = new DefaultCategoryDataset();

        for(SoLuongThang dt: list){
            model.addRow(dt.toArray());
            dcd.setValue(dt.getTong(), "Số lượng", dt.getThang());
        }
        doanhThuThangTable1.setModel(model);

        JFreeChart jchart = ChartFactory.createBarChart3D("Số lượng hàng hóa được bán trong năm "+year, "Tháng", "Số lượng", dcd, PlotOrientation.VERTICAL, true, true, false);

        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.PINK);

        ChartPanel chartPanel = new ChartPanel(jchart);

        reportPanel1.removeAll();
        reportPanel1.setLayout(new BorderLayout());
        reportPanel1.add(chartPanel, BorderLayout.NORTH);
        reportPanel1.updateUI();
    }//GEN-LAST:event_ThongKeBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DoanhThuThang;
    private javax.swing.JTabbedPane Quanly;
    private javax.swing.JPanel SoLuongThang;
    private javax.swing.JButton ThongKeBtn;
    private javax.swing.JButton ThongKeBtn1;
    private javax.swing.JTable doanhThuThangTable;
    private javax.swing.JTable doanhThuThangTable1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> namDropList;
    private javax.swing.JComboBox<String> namDropList1;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JPanel reportPanel1;
    private javax.swing.JLabel yearLabelDoanhThu;
    private javax.swing.JLabel yearLabelDoanhThu1;
    // End of variables declaration//GEN-END:variables
}
