/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Class.SanPham1;
import Class.DonNhapHang;
import Class.CTDonNhapHang;
import DBController.DBController;
import DBController.SanPhamController;
import DBController.DonNhapHangController;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quan
 */
public class QuanTri extends javax.swing.JFrame {

    /**
     * Creates new form QuanTri
     */
    public QuanTri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tDonNhapHang = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tCTDonNhapHang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNam = new javax.swing.JTextField();
        txtThang = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        find = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDSSanPham = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bReset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        pNgayHH = new javax.swing.JTextField();
        pGia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pNSX = new javax.swing.JTextField();
        pMoTa = new javax.swing.JTextField();
        bThemSP = new javax.swing.JButton();
        pSLTon = new javax.swing.JTextField();
        bCapNhat = new javax.swing.JButton();
        pSLTrenQuay = new javax.swing.JTextField();
        pNgaySX = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pTenSP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pMaSP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        tDonNhapHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đơn nhập", "Ngày lập đơn", "Nhà SX", "Người lập", "Tổng tiền", "Mã NSX"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tDonNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDonNhapHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tDonNhapHang);

        tCTDonNhapHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đơn nhập", "Mã SP", "Số lượng", "Giá nhập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tCTDonNhapHang);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel9.setText("Tháng");

        txtThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel10.setText("Năm");

        find.setBackground(new java.awt.Color(102, 153, 255));
        find.setText("Find");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("DANH SÁCH ĐƠN NHẬP HÀNG");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(find)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(find))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lịch sử nhập hàng", jPanel2);

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        tDSSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Nhà SX", "Mô tả", "Ngày sản xuất", "Ngày hết hạn", "SL tồn", "SL trên quầy", "Giá bán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tDSSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDSSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tDSSanPham);

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        jLabel7.setText("SL trên quầy");

        bReset.setBackground(new java.awt.Color(102, 153, 255));
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        jLabel11.setText("Nhà sản xuất");

        pNgayHH.setForeground(new java.awt.Color(153, 153, 153));
        pNgayHH.setText("dd-mm-yyyy");
        pNgayHH.setToolTipText("");
        pNgayHH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pNgayHHFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pNgayHHFocusLost(evt);
            }
        });

        pGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pGiaActionPerformed(evt);
            }
        });

        jLabel12.setText("Ngày hết hạn");

        jLabel3.setText("Mô tả SP");

        pNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNSXActionPerformed(evt);
            }
        });

        pMoTa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pMoTaActionPerformed(evt);
            }
        });

        bThemSP.setBackground(new java.awt.Color(102, 153, 255));
        bThemSP.setText("Thêm");
        bThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bThemSPActionPerformed(evt);
            }
        });

        pSLTon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pSLTonActionPerformed(evt);
            }
        });

        bCapNhat.setBackground(new java.awt.Color(102, 153, 255));
        bCapNhat.setText("Cập nhật");
        bCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCapNhatActionPerformed(evt);
            }
        });

        pSLTrenQuay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pSLTrenQuayActionPerformed(evt);
            }
        });

        pNgaySX.setForeground(new java.awt.Color(153, 153, 153));
        pNgaySX.setText("dd-mm-yyyy");
        pNgaySX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pNgaySXFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pNgaySXFocusLost(evt);
            }
        });

        jLabel1.setText("Mã sản phẩm");

        jLabel4.setText("Ngày sản xuất");

        jLabel5.setText("Số lượng tồn");

        jLabel2.setText("Tên sản phẩm");

        jLabel6.setText("Giá bán");

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CONCUNG");

        jLabel14.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(".com");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pMoTa))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pMaSP)
                            .addComponent(pTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pNgayHH, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pNgaySX, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pGia, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pSLTrenQuay, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13)
                                    .addComponent(pSLTon, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(bReset)
                                .addGap(23, 23, 23)
                                .addComponent(bCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel13)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel14)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pNgaySX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pSLTon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pSLTrenQuay, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pGia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pNgayHH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sản phẩm", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 843, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showDSSanPham(){
        DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Mã SP");
            model.addColumn("Tên SP");
            model.addColumn("Nha SX");
            model.addColumn("Mô tả");
            model.addColumn("Ngày SX");
            model.addColumn("Ngày HH");
            model.addColumn("SL tồn");
            model.addColumn("SL trên quầy");
            model.addColumn("Giá bán");
            
            ArrayList<SanPham1> list = null;
            list = SanPhamController.getSanPham();
            for(SanPham1 dt:list){
                model.addRow(dt.toArray());
            }
            tDSSanPham.setModel(model);
    }
    
    public boolean validateForm(){
        if(pMaSP.getText().isEmpty() || pTenSP.getText().isEmpty() || pNSX.getText().isEmpty() || pSLTon.getText().isEmpty() || pSLTrenQuay.getText().isEmpty() || pGia.getText().isEmpty()){
            return false;
        }
        return true;
    }
    
    private void bThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bThemSPActionPerformed
        // TODO add your handling code here:
        if(validateForm()){
            String maSP = pMaSP.getText();
            String tenSP = pTenSP.getText();
            String nhaSX = pNSX.getText();
            String moTa = pMoTa.getText();
            if(moTa.isEmpty()){
                moTa=null;
            }
            
            String[] dateArray;
            String ngaySX;
            String ngayHH;
            
            String dateSX = pNgaySX.getText();
            if(dateSX.isEmpty() || dateSX.equals("dd-mm-yyyy")){
                ngaySX=null;
            }else{
                dateArray = dateSX.split("/");
                ngaySX = dateArray[1]+"/"+dateArray[0]+"/"+dateArray[2];
            }

            String dateHH = pNgaySX.getText();
            if(dateHH.isEmpty() || dateHH.equals("dd-mm-yyyy")){
                ngayHH=null;
            }else{
                dateArray = dateHH.split("/");
                ngayHH = dateArray[1]+"/"+dateArray[0]+"/"+dateArray[2];
            }
            
            int slTon = Integer.parseInt(pSLTon.getText());
            int slTrenQuay = Integer.parseInt(pSLTrenQuay.getText());
            int giaBan = Integer.parseInt(pGia.getText());

            if(!SanPhamController.insert(maSP, tenSP, nhaSX, moTa, ngaySX, ngayHH, slTon, slTrenQuay, giaBan)){
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }else JOptionPane.showMessageDialog(this, "Thêm thành công");
        }else{
            JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ thông tin");
        }
    }//GEN-LAST:event_bThemSPActionPerformed

    private void bCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCapNhatActionPerformed
        // TODO add your handling code here:
        if(validateForm()){
            String maSP = pMaSP.getText();
            String tenSP = pTenSP.getText();
            String nhaSX = pNSX.getText();
            String moTa = pMoTa.getText();
            if(moTa.isEmpty()){
                moTa=null;
            }
            
            String[] dateArray;
            String ngaySX;
            String ngayHH;
            
            String dateSX = pNgaySX.getText();
            if(dateSX.isEmpty() || dateSX.equals("dd-mm-yyyy")){
                ngaySX=null;
            }else{
                dateArray = dateSX.split("-");
                ngaySX = dateArray[1]+"-"+dateArray[0]+"-"+dateArray[2];
            }

            String dateHH = pNgaySX.getText();
            if(dateHH.isEmpty() || dateHH.equals("dd-mm-yyyy")){
                ngayHH=null;
            }else{
                dateArray = dateHH.split("-");
                ngayHH = dateArray[1]+"-"+dateArray[0]+"-"+dateArray[2];
            }
            
            int slTon = Integer.parseInt(pSLTon.getText());
            int slTrenQuay = Integer.parseInt(pSLTrenQuay.getText());
            int giaBan = Integer.parseInt(pGia.getText());

            if(!SanPhamController.update(maSP, tenSP, nhaSX, moTa, ngaySX, ngayHH, slTon, slTrenQuay, giaBan)){
                JOptionPane.showMessageDialog(this, "Cập nhât thất bại");
            }else JOptionPane.showMessageDialog(this, "Cập nhật thành công");
        }else{
            JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ thông tin");
        }
        showDSSanPham();
    }//GEN-LAST:event_bCapNhatActionPerformed

    private void pGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pGiaActionPerformed

    private void pNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNSXActionPerformed

    private void pSLTonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pSLTonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pSLTonActionPerformed

    private void pSLTrenQuayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pSLTrenQuayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pSLTrenQuayActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        pMaSP.setText("");
        pTenSP.setText("");
        pSLTon.setText("");
        pNSX.setText("");
        pMoTa.setText("");
        pNgaySX.setText("dd-mm-yyyy");
        pNgayHH.setText("dd-mm-yyyy");
        pSLTrenQuay.setText("");
        pGia.setText("");
    }//GEN-LAST:event_bResetActionPerformed

    private void pMoTaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pMoTaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pMoTaActionPerformed

    
    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
            // TODO add your handling code here:
        String month = txtThang.getSelectedItem().toString();
        String year = txtNam.getText();
        if(year.length()>0){
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Mã đơn nhập");
            model.addColumn("Ngày lập đơn");
            model.addColumn("Người lập");
            model.addColumn("Tổng tiền");
            model.addColumn("NSX");
            
            ArrayList<DonNhapHang> list = null;
            list = DonNhapHangController.import_history_list(month, year);
            for(DonNhapHang dt:list){
                model.addRow(dt.toArray());
            }
            tDonNhapHang.setModel(model);
        }else{
            JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ thông tin");
        }
    }//GEN-LAST:event_findActionPerformed

    private void tDonNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDonNhapHangMouseClicked
        // TODO add your handling code here:
        int index = tDonNhapHang.getSelectedRow();
        String maDNH = tDonNhapHang.getValueAt(index, 0).toString();
       
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã DNH");
        model.addColumn("Mã SP");
        model.addColumn("Số lượng");
        model.addColumn("Giá nhập");

        ArrayList<CTDonNhapHang> list = null;
        list = DonNhapHangController.get_CTDNH_by_maDNH(maDNH);
        for(CTDonNhapHang dt:list){
            model.addRow(dt.toArray());
        }
        tCTDonNhapHang.setModel(model);
    }//GEN-LAST:event_tDonNhapHangMouseClicked

    private void tDSSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDSSanPhamMouseClicked
        // TODO add your handling code here:
        int index = tDSSanPham.getSelectedRow();

        pMaSP.setText(tDSSanPham.getValueAt(index, 0).toString());
        pTenSP.setText(tDSSanPham.getValueAt(index, 1).toString());
        pNSX.setText(tDSSanPham.getValueAt(index, 2).toString());
        
        if(tDSSanPham.getValueAt(index, 3) == null){
            pMoTa.setText("");
        }else{
            pMoTa.setText(tDSSanPham.getValueAt(index, 3).toString());
        }

        String ngaySX, ngayHH, dateSX, dateHH;
        String[] dateArray;
        
        if(tDSSanPham.getValueAt(index, 4) == null){
            dateSX="";
        }else{
            dateSX = tDSSanPham.getValueAt(index, 4).toString();
        }
        
        if(tDSSanPham.getValueAt(index, 4) == null){
            dateHH="";
        }else{
            dateHH = tDSSanPham.getValueAt(index, 5).toString();
        }
        
        if(dateSX.isEmpty()){
            ngaySX="";
        }else{
            dateArray = dateSX.split("-");
            ngaySX = dateArray[2]+"-"+dateArray[1]+"-"+dateArray[0];
        }
        if(dateHH.isEmpty()){
            ngayHH="";
        }else{
            dateArray = dateHH.split("-");
            ngayHH = dateArray[2]+"-"+dateArray[1]+"-"+dateArray[0];
        }
        
        pNgaySX.setText(ngaySX);
        pNgayHH.setText(ngayHH);
        pSLTon.setText(tDSSanPham.getValueAt(index, 6).toString());
        pSLTrenQuay.setText(tDSSanPham.getValueAt(index, 7).toString());
        pGia.setText(tDSSanPham.getValueAt(index, 8).toString());
    }//GEN-LAST:event_tDSSanPhamMouseClicked

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentShown

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        showDSSanPham();
    }//GEN-LAST:event_jPanel1ComponentShown

    private void pNgayHHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pNgayHHFocusGained
        // TODO add your handling code here:
        if(pNgayHH.getText().equals("dd-mm-yyyy")){
            pNgayHH.setText("");
            pNgayHH.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_pNgayHHFocusGained

    private void pNgayHHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pNgayHHFocusLost
        // TODO add your handling code here:
        if(pNgayHH.getText().equals("")){
            pNgayHH.setText("dd-mm-yyyy");
            pNgayHH.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_pNgayHHFocusLost

    private void pNgaySXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pNgaySXFocusGained
        // TODO add your handling code here:
        if(pNgaySX.getText().equals("dd-mm-yyyy")){
            pNgaySX.setText("");
            pNgaySX.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_pNgaySXFocusGained

    private void pNgaySXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pNgaySXFocusLost
        // TODO add your handling code here:
         if(pNgaySX.getText().equals("")){
            pNgaySX.setText("dd-mm-yyyy");
            pNgaySX.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_pNgaySXFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanTri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCapNhat;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bThemSP;
    private javax.swing.JButton find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField pGia;
    private javax.swing.JTextField pMaSP;
    private javax.swing.JTextField pMoTa;
    private javax.swing.JTextField pNSX;
    private javax.swing.JTextField pNgayHH;
    private javax.swing.JTextField pNgaySX;
    private javax.swing.JTextField pSLTon;
    private javax.swing.JTextField pSLTrenQuay;
    private javax.swing.JTextField pTenSP;
    private javax.swing.JTable tCTDonNhapHang;
    private javax.swing.JTable tDSSanPham;
    private javax.swing.JTable tDonNhapHang;
    private javax.swing.JTextField txtNam;
    private javax.swing.JComboBox<String> txtThang;
    // End of variables declaration//GEN-END:variables
}
